"""Fill the Hitachi G-TMP S0203 rev.01 VDD template (.docx) with
content generated by the VDD Drafter LLM agent.

Table-finding strategy: collect all tables with a matching header structure
and assign them in document order, rather than searching by proximity to a
heading. This avoids false matches on tables with similar-looking headers.
"""

from __future__ import annotations

import io
import logging
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Optional

logger = logging.getLogger(__name__)

_TEMPLATE_PATH = (
    Path(__file__).parent.parent.parent
    / "docs"
    / "hitachi-reference-docs"
    / "06. VDD"
    / "G-TMP_S0203_01_EN.docx"
)

_NS = "http://schemas.openxmlformats.org/wordprocessingml/2006/main"


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------


def fill_vdd_template(
    markdown: str,
    release_tag: str,
    repo: str,
    head_sha: str,
    release_date: Optional[str] = None,
    module_versions: Optional[list] = None,
    template_path: Optional[Path] = None,
) -> Optional[bytes]:
    try:
        from docx import Document  # type: ignore
    except ImportError:
        logger.warning("python-docx not installed — skipping .docx generation")
        return None

    path = template_path or _TEMPLATE_PATH
    if not path.exists():
        logger.warning("VDD template not found at %s", path)
        return None

    doc = Document(str(path))
    date_str = release_date or datetime.now(timezone.utc).strftime("%d-%b-%Y").upper()
    project_name = repo.split("/")[-1] if "/" in repo else repo

    _replace_fields(doc, project_name, release_tag, date_str)
    sections = _parse_markdown(markdown)

    # --- Prose sections -------------------------------------------------------
    intro = sections.get("Introduction", {})
    _fill_after_heading(doc, "Purpose",
                        _clean(intro.get("Purpose", "")))
    _fill_after_heading(doc, "Applicability",
                        _clean(intro.get("Applicability", "")))
    _fill_after_heading(doc, "Description of Changes from the Previous Revision",
                        _clean(intro.get("Description of Changes from the Previous Revision", "")))
    _fill_limitation_table(doc,
                           _clean(sections.get("Sw Version Limitation", {}).get("_body", "")))
    _fill_after_heading(doc, "Installation Instructions",
                        _clean(sections.get("Installation Instructions", {}).get("_body", "")))

    # --- §2.2.1  SCI table  (header: "CI Description | CI Name | CI Version …") ---
    if module_versions:
        sci_tables = _find_tables_by_header(doc, ["ci description", "ci name", "ci version"])
        if sci_tables:
            for mv in module_versions:
                _add_row(sci_tables[0], [
                    mv.name, mv.name, mv.version, release_tag,
                    mv.source_path or "",
                ])

    # --- §3  Documentation tables  (header: "document title | doc code tc …") ---
    doc3 = sections.get("Documentation Related to the Baseline", {})
    doc_tables = _find_tables_by_header(doc, ["document title", "doc code tc"])
    _subsections_to_tables(doc_tables, [
        doc3.get("Requirements specification Documents", ""),
        doc3.get("Software conception, design, programming Documents", ""),
        doc3.get("Testing Documentation", ""),
        doc3.get("Other documents", ""),
    ], cols=["Document title", "Doc code TC", "Revision", "TC Document Lifecycle state"])

    # --- §4  Build environment table  (header: "tool/script file | tool version …") ---
    build = sections.get("Sw Version Build", {})
    build_tables = _find_tables_by_header(doc, ["tool", "version"])
    if build_tables:
        text = build.get("Build Environment for Reproducibility", "")
        for line in _bullet_lines(text):
            tool, _, ver = line.partition(":")
            _add_row(build_tables[0], [tool.strip(), ver.strip(), ""])

    # --- §5  Changes tables  (header: "identifier | title | status …") ---
    changes = sections.get("Changes Incorporated", {})
    change_tables = _find_tables_by_header(doc, ["identifier", "title"])
    if change_tables:
        taken = _bullet_lines(
            changes.get("List of changes taken into account in this SW version", "")
        )
        for i, item in enumerate(taken, 1):
            _add_row(change_tables[0], [str(i), item, "Closed", "Verdict", "Change", "No"])
    if len(change_tables) > 1:
        not_taken = _bullet_lines(
            changes.get("List of changes not taken into account in this sw version", "")
        )
        for i, item in enumerate(not_taken, 1):
            _add_row(change_tables[1], [str(i), item, "Verdict", "Change", "No"])

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


# ---------------------------------------------------------------------------
# Helpers — field replacement
# ---------------------------------------------------------------------------


def _para_text(para) -> str:
    return "".join(r.text or "" for r in para.runs)


def _set_para_text(para, text: str) -> None:
    if not para.runs:
        return
    para.runs[0].text = text
    for run in para.runs[1:]:
        run.text = ""


def _replace_in_para(para, subs: dict) -> None:
    full = _para_text(para)
    replaced = full
    for old, new in subs.items():
        replaced = replaced.replace(old, new)
    if replaced != full:
        _set_para_text(para, replaced)


def _replace_fields(doc, project_name: str, tag: str, date_str: str) -> None:
    subs = {
        "<Project Name>": project_name,
        "<Issue Date>": date_str,
        "<Author_Owner>": "Verdict (auto-generated)",
        "<Author Designation>": "AI Release Assistant",
        "<Verifier>": "_to be assigned_",
        "<Verifier Designation>": "_to be assigned_",
        "<Approver>": "_to be assigned_",
        "<Approver Designation>": "_to be assigned_",
        "<AuthorIser>": "_to be assigned_",
        "<Authoriser Designation>": "_to be assigned_",
        "<baseline_name>": f"{project_name}-{tag}",
        "{A}": "00",
        "{dd-MMM-yyyy}": date_str,
        "{Author}": "Verdict",
        "{Verifier}": "_to be assigned_",
        "{Approver}": "_to be assigned_",
        "{Authorizer}": "_to be assigned_",
        # Remove the "not applicable" placeholder — the actual changes text is injected via _fill_after_heading
        "{Not applicable for the first issue}.": "",
        # Fill the §1.1 and §1.2 inline placeholders
        "{insert here Module/Application/CI, System name, references}": f"{project_name} {tag}",
        "{insert here the baseline identifier. In addition it must be referenced any starting reference baseline}": f"{project_name}-{tag}",
    }
    for para in doc.paragraphs:
        _replace_in_para(para, subs)
    for table in doc.tables:
        for row in table.rows:
            for cell in row.cells:
                for para in cell.paragraphs:
                    _replace_in_para(para, subs)
    # Fix headers/footers (e.g. "<Project Name>" in every page header)
    for section in doc.sections:
        for hf in (section.header, section.footer):
            for para in hf.paragraphs:
                _replace_in_para(para, subs)
            for tbl in hf.tables:
                for row in tbl.rows:
                    for cell in row.cells:
                        for para in cell.paragraphs:
                            _replace_in_para(para, subs)


# ---------------------------------------------------------------------------
# Helpers — markdown parsing
# ---------------------------------------------------------------------------


def _clean(text: str) -> str:
    lines = [re.sub(r"^#{1,4}\s*", "", l) for l in text.splitlines()]
    return "\n".join(l for l in lines if l.strip())


def _bullet_lines(text: str) -> List[str]:
    return [
        re.sub(r"^[-•*]\s*", "", l).strip()
        for l in text.splitlines()
        if l.strip() and not l.strip().startswith("#")
    ]


def _parse_markdown(markdown: str) -> Dict[str, Dict[str, str]]:
    result: Dict[str, Dict[str, str]] = {}
    section: Optional[str] = None
    subsection: Optional[str] = None
    buf: List[str] = []

    def _flush():
        if section is None:
            return
        text = "\n".join(buf).strip()
        result.setdefault(section, {})
        key = subsection if subsection else "_body"
        result[section][key] = result[section].get(key, "") + "\n" + text

    for line in markdown.splitlines():
        if line.startswith("## "):
            _flush()
            section = line[3:].strip()
            subsection = None
            buf = []
        elif line.startswith("### "):
            _flush()
            subsection = line[4:].strip()
            buf = []
        else:
            buf.append(line)
    _flush()
    return result


# ---------------------------------------------------------------------------
# Helpers — prose injection
# ---------------------------------------------------------------------------


def _find_heading_para(doc, heading_text: str):
    """Find a section heading paragraph, skipping TOC entries.

    Prefers paragraphs with a Heading style; falls back to any non-TOC
    paragraph if no styled heading is found.
    """
    ht = heading_text.lower()
    # First pass: actual Heading styles only (never appear in TOC)
    for para in doc.paragraphs:
        style = para.style.name.lower() if para.style else ""
        if style.startswith("heading") and ht in para.text.lower():
            return para
    # Second pass: any paragraph that is NOT a TOC entry
    for para in doc.paragraphs:
        style = para.style.name.lower() if para.style else ""
        if "toc" in style:
            continue
        if ht in para.text.lower():
            return para
    return None


def _inject_after(para, lines: List[str]) -> None:
    from docx.oxml import OxmlElement
    for line in reversed(lines):
        p = OxmlElement("w:p")
        r = OxmlElement("w:r")
        t = OxmlElement("w:t")
        t.text = line
        t.set("{http://www.w3.org/XML/1998/namespace}space", "preserve")
        r.append(t)
        p.append(r)
        para._element.addnext(p)


def _fill_after_heading(doc, heading: str, text: str) -> None:
    if not text.strip():
        return
    para = _find_heading_para(doc, heading)
    if para is None:
        logger.debug("Heading not found: %s", heading)
        return
    lines = [l for l in text.splitlines() if l.strip()]
    _inject_after(para, lines)


# ---------------------------------------------------------------------------
# Helpers — table finding (by header keywords, in document order)
# ---------------------------------------------------------------------------


def _table_header_lower(table) -> str:
    if not table.rows:
        return ""
    return " ".join(c.text.strip().lower() for c in table.rows[0].cells)


def _find_tables_by_header(doc, keywords: List[str]) -> List:
    """Return all tables whose first row contains ALL keywords (case-insensitive),
    in document order."""
    result = []
    for table in doc.tables:
        h = _table_header_lower(table)
        if all(kw.lower() in h for kw in keywords):
            result.append(table)
    return result


def _add_row(table, values: List[str]) -> None:
    row = table.add_row()
    for i, val in enumerate(values):
        if i < len(row.cells):
            row.cells[i].text = str(val)


def _fill_limitation_table(doc, text: str) -> None:
    """Fill §6 SW Version Limitation table (pre-numbered rows 1/2/3)."""
    if not text.strip():
        return
    items = [l.strip() for l in text.splitlines() if l.strip()]
    tables = _find_tables_by_header(doc, ["number", "limitation"])
    if not tables:
        _fill_after_heading(doc, "Sw Version Limitation", text)
        return
    table = tables[0]
    data_rows = [r for r in table.rows[1:] if r.cells[0].text.strip() in ("1", "2", "3")]
    for row, item in zip(data_rows, items):
        if len(row.cells) > 1:
            row.cells[1].text = item
        if len(row.cells) > 2:
            row.cells[2].text = "auto-generated"
    for i, item in enumerate(items[len(data_rows):], start=len(data_rows) + 1):
        _add_row(table, [str(i), item, "auto-generated"])


def _subsections_to_tables(tables: list, contents: List[str],
                            cols: List[str]) -> None:
    """Fill N tables with N content strings, one per sub-section."""
    for table, text in zip(tables, contents):
        if not text.strip():
            continue
        for line in _bullet_lines(text):
            if line:
                vals = [line] + [""] * (len(cols) - 1)
                _add_row(table, vals)
